#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ByteDevice

EXTRA_COMPONENT_DIRS := components

include $(MDF_PATH)/esp-idf/make/project.mk

